### ISSUE TITLE
 Method Zizaco\Entrust\MigrationCommand::handle() does not exist  

### ISSUE THREAD

**Issue by zuijiu997** [Zizaco/entrust#836] opened 2017-09-03 13:00 UTC
php artisan entrust:migration throw this ReflectionException
 Method Zizaco\Entrust\MigrationCommand::handle() does not exist

**Comment by dokicro** [comment] 2017-09-04 12:26
Same here... Any solution?

**Comment by puneetchoudhary7** [comment] 2017-09-10 11:07
Thanks a lot @dokicro. You save my day.

**Comment by THEMBOCHARLES** [comment] 2017-10-02 10:49
Yes, It worked. Thank you

**Comment by erayaydin** [comment] 2017-10-04 00:16
This should be created PR and merged with new tag for Laravel 5.5 Support

**Comment by Zizaco** [comment] 2017-11-13 22:34
Closed since #840 was merged

**Closed by Zizaco** 2017-11-13 22:34 UTC

**Comment by diegocar448** [comment] 2017-12-06 12:27
Funciona com a versão 5.5 do Laravel?

**Comment by faiverson** [comment] 2017-12-06 15:03
Yes, it works! You can use "zizaco/entrust": "dev-master" instead

**Comment by diegocar448** [comment] 2017-12-06 16:40
Do you have any tutorials to help me set up? Because following the doc I'm having errors the structure changes laravel 5.4 changes a little getting different from the documentation.

**Comment by faiverson** [comment] 2017-12-06 16:51
I don't have a tutorial.
I'd suggest to try in a clean laravel 5.5 so you can see if the problem is the package or you are having other problems.
What you need to do is:
Add "zizaco/entrust": "dev-master" and run composer update
You don't need to add nothing in app.php in laravel 5.5
Then run vendor:publish and select the package
Once the config file is added, you can run php artisan entrust:migration and the the migrations.
Make sure that you User, Role and Permission models are fine and the namespace/path are correct in the config file.

Hope this help!

**Comment by diegocar448** [comment] 2017-12-06 19:03
It is possible to have the same ACL result using Middleware? I had done a long ago doing so, would the ACL have any more advantage than Middleware?

https://github.com/diegocar448/CodeDelivery/blob/master/app/Http/routes.php

**Comment by faiverson** [comment] 2017-12-06 20:05
Not sure what you are asking. What is ACL for you? What are you trying to compare? Please be more explanatory.

**Comment by diegocar448** [comment] 2017-12-07 03:29
I talked about access level, when we separated accessibility, responsibilities, administrator levels, clients, user ..... does not ACL do that too?

**Comment by faiverson** [comment] 2017-12-07 03:52
There are different ways to handle accessibility and responsibilities, it will depend on you and your project. You can cover accessibility with Gates and Policies for example.
This package provides you a way to handle roles and permissions in views and you are extending the models to easy assign/attach and remove/deattach permissions and roles.
It is not better or worse, it depends on you and your taste.

**Comment by soubhikchatterjee** [comment] 2018-02-26 09:18
Works like a charm...

**Comment by naveednasib** [comment] 2018-04-25 05:37
pro yes its work (y)

**Comment by ecabrales** [comment] 2018-07-19 22:43
thenks! helpful for fix this bug with fire method :+1:

**Comment by karimsamir** [comment] 2018-09-12 08:12
The error still exists after install it using
composer require zizaco/entrust:5.2.x-dev

**Comment by viniciussvl** [comment] 2018-09-13 16:00
> I found solution by @justem007 take a look here: #826
> 
> "Go to the file (vendor-> zizaco-> entrust-> src-> commands-> MigrationCommand.php and change the "fire" method to "handle" and after the command "php artisan entrust: migration" will be generated Migration and just run the "php artisan migrate" command that the tables will be generated in your database."

thaaaaaaaaaanks

**Comment by walfter** [comment] 2018-09-24 18:19
> The error still exists after install it using
> composer require zizaco/entrust:5.2.x-dev

Thanks!=)

**Comment by vijaymee05** [comment] 2019-02-09 09:19
> handle

Thanks a ton :+1: 
It works for me

**Comment by vijaymee05** [comment] 2019-02-09 09:20
> I found solution by @justem007 take a look here: #826
> 
> "Go to the file (vendor-> zizaco-> entrust-> src-> commands-> MigrationCommand.php and change the "fire" method to "handle" and after the command "php artisan entrust: migration" will be generated Migration and just run the "php artisan migrate" command that the tables will be generated in your database."

Thanks a ton :+1: 
It works for me

**Comment by MuriungiPatrick** [comment] 2019-06-19 15:42
Checkout for this file inside zizaco folder.  change the fire method to Handle. check below
&nbsp;
![fire-to-handle](https://user-images.githubusercontent.com/11283502/59779937-d5833500-92c1-11e9-934e-00aeb6deed8b.PNG)

**Comment by kumarrahul-rkv** [comment] 2019-06-26 10:03
> I found solution by @justem007 take a look here: #826
> 
> "Go to the file (vendor-> zizaco-> entrust-> src-> commands-> MigrationCommand.php and change the "fire" method to "handle" and after the command "php artisan entrust: migration" will be generated Migration and just run the "php artisan migrate" command that the tables will be generated in your database."

Thanks, It worked for me.

**Comment by pcbimon** [comment] 2019-07-04 07:38
> I found solution by @justem007 take a look here: #826
> 
> "Go to the file (vendor-> zizaco-> entrust-> src-> commands-> MigrationCommand.php and change the "fire" method to "handle" and after the command "php artisan entrust: migration" will be generated Migration and just run the "php artisan migrate" command that the tables will be generated in your database."

Worked ... Thanks 👍

**Comment by sdebarun** [comment] 2019-07-12 10:59
The problem of calling handle method during the the migration file s creation still persists. Though the solution @dokicro provided worked. But this should be fixed or at least be mentioned in the documentation.

**Comment by alexeyp0708** [comment] 2019-07-31 10:16
I confirm. The problem exists when installing "zizaco / entrust": "5.2.x-dev". If you change the version to "dev-master" and composer update, the problem is solved.
